title: Settings
fields:
  -
    handle: template
    field:
      type: template
      display: Template
      localizable: false
      folder: templates
      validate:
        - required
  -
    handle: layout
    field:
      type: template
      display: Layout
      localizable: false
      default: layout/default
      hide: true
      folder: layout
      visibility: hidden
